<?php
// Zentrale Konfiguration
return [
    "current_version" => "1.4",
    "api_url" =>
        "https://" . $_SERVER["HTTP_HOST"] . "/shine-snatch/shine-snatch.php",
    "default_theme" => "Gold",
    "admin_password_hash" =>
        '$2y$12$VQBvnaRmyhYYorVtby/J9ukVJqq7lT.7P5eST.UrzodjdJ8Ki9iZC',
    "snatchmaster" => ["517115001736134676"],
    "kartenzusatz" => [
        "der Verderbnis",
        "der Einsicht",
        "des Glücks",
        "des Zorns",
        "des betrunkenen Barden",
        "der unendlichen Weisheit",
        "des Wahnsinns",
        "der Verdammnis",
        "des Schreckens",
        "der Apokalypse",
        "der Ewigkeit",
        "des Schicksals",
        "der Zerstörung",
        "der Hoffnung",
        "der Weisheit",
        "des Blutes",
        "des Chaos",
        "der Schatten",
        "des Lichts",
        "der Täuschung",
        "des Neides",
        "der Gier",
        "des Hochmuts",
        "der Verzweiflung",
        "des Triumphes",
        "des Hochverrats",
        "der Rache",
        "der Finsternis",
        "der Gerechtigkeit",
        "der Alpträume",
        "des Grauens",
        "des Keks-Entzugs",
        "der totalen Verwirrung",
        "des gepflegten Müßiggangs",
        "der chronischen Pleite",
        "des ewigen Hungers",
        "der Peinlichkeit",
        "des stumpfen Schwerts",
        "des nassen Handtuchs",
        "der schlaflosen Nächte",
        "des blauen Auges",
        "der Bürokratie",
        "der Drachen-Allergie",
        "der gepanzerten Socke",
        "des puren Zufalls",
        "des leeren Beutels",
        "der Schreibtisch-Helden",
        "des Mimik-Verdachts",
        "der schmerzhaften Wahrheit",
        "der Vergessenheit",
        "der Drachenreiter",
        "der Apfelstrudel-Sucht",
    ],
];
?>
